export const DUMMY_LEADERBOARD = [
  {
    user: {
      full_name: "James Gomez",
      highschool: "Group",
      choosen_university_one: "Carrillo-Lewis",
      choosen_major_one: "Town planner",
      choosen_university_three: "Clark PLC",
      choosen_major_three: "Records manager",
    },
    totalPoints: 767,
    rank: 1,
  },
  {
    user: {
      full_name: "Jennifer Armstrong",
      highschool: "PLC",
      choosen_university_one: "Wilson, Horton and Hudson",
      choosen_major_one: "Charity fundraiser",
      choosen_university_two: "Fischer-Mejia",
    },
    totalPoints: 345,
    rank: 2,
  },
  {
    user: {
      full_name: "Daniel Monroe",
      highschool: "Ltd",
      choosen_university_one: "Long PLC",
      choosen_major_one: "Visual merchandiser",
      choosen_university_two: "Wood-Wright",
      choosen_university_three: "Smith-Johnson",
      choosen_major_three: "Engineer, aeronautical",
    },
    totalPoints: 548,
    rank: 3,
  },
  {
    user: {
      full_name: "Misty Knight",
      highschool: "Inc",
      choosen_university_one: "Burke-Arnold",
      choosen_major_one: "Solicitor",
      choosen_major_three: "Surveyor, rural practice",
    },
    totalPoints: 80,
    rank: 4,
  },
  {
    user: {
      full_name: "Bernard Nguyen",
      highschool: "and Sons",
      choosen_university_one: "Walker-Robertson",
      choosen_major_one: "Call centre manager",
      choosen_university_two: "Jones Ltd",
      choosen_university_three: "Wells and Sons",
    },
    totalPoints: 381,
    rank: 5,
  },
  {
    user: {
      full_name: "Victoria Robinson",
      highschool: "PLC",
      choosen_university_one: "Wells, Gates and Harris",
      choosen_major_one: "Energy engineer",
      choosen_university_two: "Hayes, Hernandez and Murray",
      choosen_major_three: "Chief Marketing Officer",
    },
    totalPoints: 280,
    rank: 6,
  },
  {
    user: {
      full_name: "Anna Campbell",
      highschool: "LLC",
      choosen_university_one: "Humphrey, Harris and Kim",
      choosen_major_one: "Museum education officer",
      choosen_university_two: "Mitchell, Aguirre and Miller",
      choosen_major_two: "Wellsite geologist",
      choosen_major_three: "Stage manager",
    },
    totalPoints: 759,
    rank: 7,
  },
  {
    user: {
      full_name: "Jodi Reeves",
      highschool: "LLC",
      choosen_university_one: "Lewis PLC",
      choosen_major_one: "Politician's assistant",
      choosen_university_two: "Johnson-Thomas",
      choosen_major_two: "Occupational psychologist",
    },
    totalPoints: 239,
    rank: 8,
  },
  {
    user: {
      full_name: "Emily Fowler",
      highschool: "Group",
      choosen_university_one: "Page, Landry and Curtis",
      choosen_major_one: "Loss adjuster, chartered",
      choosen_university_two: "Wolfe-Davis",
      choosen_major_two: "Radiation protection practitioner",
    },
    totalPoints: 110,
    rank: 9,
  },
  {
    user: {
      full_name: "Angela Patterson",
      highschool: "Inc",
      choosen_university_one: "Glover-Freeman",
      choosen_major_one: "Museum education officer",
      choosen_major_three: "Multimedia programmer",
    },
    totalPoints: 908,
    rank: 10,
  },
];
