// components
import Iconify from "@components/Iconify";

// data
import { questions } from "@data/latihan-soal";

// libs
import type { Metadata } from "next";

const categoryMap: Record<string, string> = {
  pu: "Penalaran Umum",
  pk: "Pengetahuan Kuantitatif",
  ppu: "Pengetahuan dan Pemahaman Umum",
  pbm: "Pemahaman Bacaan dan Menulis",
};

export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const { slug } = params;

  const title = `${categoryMap[slug[0]] || "Latihan Soal"} | Bang Soal`;
  return {
    title,
    description: "Generated by create next app",
  };
}

export default function LatihanSoal({
  params,
}: Readonly<{ params: { slug: string } }>) {
  return (
    <main className="flex min-h-screen flex-col items-stretch py-10">
      <div className="flex flex-col gap-5 px-10">
        <div className="flex flex-col gap-1">
          <h1 className="text-3xl font-700 text-content-100">
            {categoryMap[params.slug[0]]}
          </h1>
          <h2 className="text-xl font-600 text-content-300">
            Barisan Bilangan
            <button className="group ml-1 inline-flex items-center gap-1 rounded-full px-2 text-sm font-500 text-surface-400 hover:bg-emerald-400 hover:text-emerald-100">
              <Iconify icon="ph:download-simple-bold" />
              <p className="hidden group-hover:block">Download</p>
            </button>
          </h2>
          <h2 className="text-xl font-600 text-content-300">UTBK 2022</h2>
        </div>
        <p>
          Waktu tempuh yang berhasil diraih oleh atlet sepeda pada latihan
          kesatu sampai ketiga secara berturut-turut adalah 27, 27, 26 menit,
          sedangkan pada latihan kelima sampai ketujuh adalah 21, 17, 12 menit.
          Jika tren waktu tersebut bersifat konstan, berapa waktu tempuh pada
          latihan keempat?
        </p>
      </div>
    </main>
  );
}
