import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/Navbar";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${inter.className} relative flex flex-col bg-surface-100`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
