import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Footer from "./components/Footer";
import Nav from "./components/Navbar";
import "./globals.scss";
import Providers from "./providers";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${quicksand.className} relative flex flex-col bg-surface-100`}
      >
        <Providers>
          <Nav />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
