export const UNI_LOGOS = [
  "/logos/uni1.svg",
  "/logos/uni2.svg",
  "/logos/uni3.svg",
];

export const SIGNUP_COPYWRITING = {
  login: {
    header: "Get back in the game!",
    caption:
      "Sign in with your Bang Soal account to start practicing for your UTBK!",
    anchor: "A new user? Make an account.",
  },
  register: {
    header: "Get in the game!",
    caption: "Create an account to start using Bang Soal today! ",
    anchor: "Already a user? Sign in.",
  },
};

import { PTN } from "@/types";

export const DUMMY_PRODI = [
  "TEKNIK SIPIL",
  "TEKNIK MESIN",
  "TEKNIK INDUSTRI",
  "AGRIBISNIS",
  "AGROTEKNOLOGI",
  "PERIKANAN",
  "KESEHATAN MASYARAKAT",
  "AKUAKULTUR",
  "SUMBER DAYA AKUATIK",
  "TEKNOLOGI HASIL PERTANIAN",
  "ILMU KELAUTAN",
  "TEKNOLOGI INFORMASI",
  "GIZI",
  "EKONOMI PEMBANGUNAN",
  "ILMU ADMINISTRASI NEGARA",
  "SOSIOLOGI",
  "ILMU KOMUNIKASI",
  "MANAJEMEN",
  "AKUNTANSI",
  "ILMU HUKUM",
];

export const DUMMY_PTN: PTN[] = [
  {
    name: "UNIVERSITAS TEUKU UMAR",
    href: "https://sidata-ptn-snpmb.bppp.kemdikbud.go.id/ptn_sb.php?ptn=113",
    prodi: [
      "TEKNIK SIPIL",
      "TEKNIK MESIN",
      "TEKNIK INDUSTRI",
      "AGRIBISNIS",
      "AGROTEKNOLOGI",
      "PERIKANAN",
      "KESEHATAN MASYARAKAT",
      "AKUAKULTUR",
      "SUMBER DAYA AKUATIK",
      "TEKNOLOGI HASIL PERTANIAN",
      "ILMU KELAUTAN",
      "TEKNOLOGI INFORMASI",
      "GIZI",
      "EKONOMI PEMBANGUNAN",
      "ILMU ADMINISTRASI NEGARA",
      "SOSIOLOGI",
      "ILMU KOMUNIKASI",
      "MANAJEMEN",
      "AKUNTANSI",
      "ILMU HUKUM",
    ],
  },
  {
    name: "UNIVERSITAS SAMUDRA",
    href: "https://sidata-ptn-snpmb.bppp.kemdikbud.go.id/ptn_sb.php?ptn=114",
    prodi: [
      "AGROTEKNOLOGI",
      "AGRIBISNIS",
      "AKUAKULTUR",
      "PENDIDIKAN MATEMATIKA",
      "PENDIDIKAN FISIKA",
      "PENDIDIKAN KIMIA",
      "PENDIDIKAN BIOLOGI",
      "TEKNIK MESIN",
      "TEKNIK SIPIL",
      "TEKNIK INDUSTRI",
      "INFORMATIKA",
      "MATEMATIKA",
      "FISIKA",
      "KIMIA",
      "BIOLOGI",
      "HUKUM",
      "EKONOMI MANAJEMEN",
      "EKONOMI PEMBANGUNAN",
      "PENDIDIKAN SEJARAH",
      "PENDIDIKAN GEOGRAFI",
      "PENDIDIKAN JASMANI",
      "PENDIDIKAN GURU SEKOLAH DASAR",
      "PENDIDIKAN BAHASA INGGRIS",
      "PENDIDIKAN BAHASA INDONESIA",
      "AKUNTANSI",
    ],
  },
  {
    name: "ISBI ACEH",
    href: "https://sidata-ptn-snpmb.bppp.kemdikbud.go.id/ptn_sb.php?ptn=115",
    prodi: [
      "SENI KARAWITAN",
      "SENI TARI",
      "SENI TEATER",
      "SENI RUPA MURNI",
      "KRIYA SENI",
      "DESAIN KOMUNIKASI VISUAL",
    ],
  },
];
